[project]
name = "ai-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sushil Chand", email = "sushilchand@Sushils-MacBook-Air.local" }
]
requires-python = ">=3.12"
dependencies = [
    "groq>=1.7.0",
    "langchain-text-splitters>=1.1.2",
    "numpy>=2.5.3",
    "pre-commit>=4.6.2",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.1",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
ai-engineering = "ai_engineering:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"

[tool.isort]
profile = "black"
